return {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
        -- add more things to the ensure_installed table protecting against community packs modifying it
        opts.ensure_installed = require("astronvim.utils").list_insert_unique(opts.ensure_installed, {
            "awk",
            "bash",
            "c",
            "cpp",
            "c_sharp",
            "cmake",
            "css",
            "diff",
            "dockerfile",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "html",
            "http",
            "ini",
            "java",
            "json",
            "lua",
            "luadoc",
            "make",
            "markdown",
            "passwd",
            "perl",
            "python",
            "regex",
            "rust",
            "sql",
            "toml",
            "vim",
            "vimdoc",
            "yaml",
        })
    end,
}
